// #include "SimplexNoise2D.hlsl"
// #include "ClassicNoise2D.hlsl"

#pragma kernel Effect

struct vertex
{
    float2 position;
    float height;
};

RWStructuredBuffer<vertex> vertex_buffer;
uint vertex_count;

cbuffer fx_params
{
    float size;
    float steepness;
    int operation; // Set, Subtract, Add, Multiply
}

float Solve(float2 p)
{
    /*  Alter the Size of the Noise
     *
     *  Make this less confusing for the user, by having
     *  a smaller Size value return a smaller noise texture.
     *
     *  Technically a lower Size value only samples a smaller
     *  region of the noise. However, its pretty fucking stupid to
     *  present the user with a "Noise Size" slider, for Small<-->Big
     *  and when they select "Big" it effectively zooms out, making it
     *  appear to be smaller. Very stupid.
     */
    float noise_size = 1.0 - size; // 0-1 -> 1-0
    p *= noise_size;

    // float noise = SimplexNoise(p) * steepness;
    float noise = 0;

    return noise;
}

vertex ApplyOperation(vertex vtx, float solved)
{
    switch (operation)
    {
    case 0:
        // Set - Overwrites any existing height
        vtx.height = solved;
        break;

    case 1:
        // Subtract - Reduces existing height by solved
        vtx.height -= solved;
        break;

    case 2:
        // Add - Increases existing height by solved
        vtx.height += solved;
        break;

    case 3:
        // Multiply - Scales existing height by solved
        vtx.height *= solved;
        break;

    default: return vtx;
    }
    return vtx;
}

[numthreads(64,1,1)]
void Effect(uint3 id : SV_DispatchThreadID)
{
    uint index = id.y * 8 + id.x;
    if (index >= vertex_count)
    {
        return;
    }
    vertex vtx = vertex_buffer[index];

    float solved_height = Solve(vtx.position); // calculate height at this position
    vtx = ApplyOperation(vtx, solved_height);
    vertex_buffer[index] = vtx; // return
}
