using System;
using System.IO;
using System.Text;
using DataTypes;
using Internal;
using Internal.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;
using UnityEngine.UIElements;
using Object = UnityEngine.Object;

namespace ConfigEditor {
public class SimpleEditorController : MonoBehaviour {
    
    // IMPORTANT - not ready for general use by others
    // this class is designed to write a MyConfig.json to Application.persistentDataPath
    // on my linux installation, that file is placed into /home/hapi/.config/unity3d/DefaultCompany/Voro/MyConfig.json
    // I have manually copied that file over into the projects /Resources/Configs/MyConfig.json in order
    // later on when the Voro UnityProject is loaded for the first time, these .json Resources will be 
    // moved over into the persistentDataPath, and Voro will no longer read from Resources
    
    VisualElement _ui;
    VisualElement _configContainer;
    
    Button _slopeButton;
    Button _noiseButton;
    Button _terraceButton;

    JsonConfig _jsonConfig;
    IConfig[] _configs;
    
    void Awake() {
        _ui = GetComponent<UIDocument>().rootVisualElement;
        _configContainer = _ui.Q<VisualElement>("ConfigContainer");
        
        // JsonConfig is given the name of the config file to read, which loads its IConfig[]
        _jsonConfig = new JsonConfig("MyConfig");
        _configs = _jsonConfig.Configs;
    }
    
    void OnEnable() {
        
        // the elements for the config container will be created automatically
        
        _slopeButton = _configContainer.Q<Button>("slopeBtn");
        _noiseButton = _configContainer.Q<Button>("noiseBtn");
        _terraceButton = _configContainer.Q<Button>("terraceBtn");
        
        // set the label of each button by reading the config
        // JsonConfig has constructed each of the IConfig structs
        for (var i = 0; i < _configs.Length; i++) {
            // read the current configuration
            IConfig cfg = _configs[i];
            
            if (cfg is SlopeCfg slope) {
                _slopeButton.text = slope.ToString();
            }
            else if (cfg is NoiseCfg noise) {
                _noiseButton.text = noise.ToString();
            }
            else if (cfg is TerraceCfg terrace) {
                _terraceButton.text = terrace.ToString();
            }
        }
        
        // at this point, the editor can do its thing, and the json data file gets modified
        ModifyJson();
        
        // the editor can now generate the new json file, as the editor has made all its changes
        // this means that voros can be generated by whatever the user did in this editor
        WriteJson();
    }

    void ModifyJson() {
        // 
    }

    void WriteJson() {
        // getting data from the json was done like this
        // 1) ResourceHelper.LoadResource<TextAsset>("Points/LineTable")
        // 2) JObject root = JObject.Parse(data.text);
        // 3) JArray configArr = (JArray)root["config"];
        // 4) JObject obj = configArr[i] as JObject;
        //  5) JProperty prop = obj.Properties().First();
        
        StringBuilder sb = new StringBuilder();
        StringWriter sw =  new StringWriter(sb);
        // write path "Resources/Configs/MyConfig.json"
        using (JsonWriter writer = new JsonTextWriter(sw)) {
            writer.Formatting = Formatting.Indented;
            
            writer.WriteStartObject();
            
            writer.WritePropertyName("config");
            writer.WriteStartArray();
            for (var i = 0; i < _configs.Length; i++) {
                IConfig cfg = _configs[i];
                
                // write each IConfig into the array
                writer.WriteStartObject();

                string name = "";
                if (cfg is SlopeCfg slope) {
                    name = "slope";
                }
                else if (cfg is NoiseCfg noise) {
                    name = "noise";
                }
                else if (cfg is TerraceCfg terrace) {
                    name = "terrace";
                }
                writer.WritePropertyName(name);
                
                var token = JToken.FromObject(cfg);
                token.WriteTo(writer);
                
                writer.WriteEndObject();
            }            
            writer.WriteEndArray();
            
            writer.WriteEndObject();
        }

        // exporting doesnt need to always happen while testing
        bool doExport = true;

        if (doExport) {
            var json = sb.ToString();
            var fileName = "MyConfig.json";
            var path = Path.Combine(Application.persistentDataPath, fileName);
            File.WriteAllText(path, json);
            Debug.Log($"Editor wrote to: {path}");
        }

    }
}
}