#include "FXCommon.hlsl"

#pragma kernel CSMain

cbuffer Params
{
    float Height;
}

float Solve(float2 uv)
{
    return Height;
}

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float2 uv = GetUV(id);
    int2 coord = int2(id.xy);

    float solvedHeight = Solve(uv);
    float origHeight = Result[coord].r;
    solvedHeight = ApplyOperation(origHeight, solvedHeight);

    Result[coord] = float4(solvedHeight, solvedHeight, solvedHeight, 1.0);

    /*
    uint index = id.y * 8 + id.x;
    if (index >= vertex_count)
    {
        return;
    }
    vertex vtx = vertex_buffer[index];
    float solved_height = Solve(); // calculate height at this position
    vtx = ApplyOperation(vtx, solved_height);
    vertex_buffer[index] = vtx; // return*/
}
