#include "SimplexNoise2D.hlsl"
#include "ClassicNoise2D.hlsl"
#include "FXCommon.hlsl"

#pragma kernel CSMain

cbuffer Params
{
    float Size;
    float Steepness;
}

float Solve(float2 uv)
{
    /*  Alter the Size of the Noise
     *
     *  Make this less confusing for the user, by having
     *  a smaller Size value return a smaller noise texture.
     *
     *  Technically a lower Size value only samples a smaller
     *  region of the noise. However, its pretty fucking stupid to
     *  present the user with a "Noise Size" slider, for Small<-->Big
     *  and when they select "Big" it effectively zooms out, making it
     *  appear to be smaller. Very stupid.
     */
    float noiseSize = 1.0 - Size; // 0-1 -> 1-0
    uv *= noiseSize;
    float noise = SimplexNoise(uv) * Steepness;
    return noise;
}

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float2 uv = GetUV(id);
    int2 coord = int2(id.xy);

    float origHeight = Result[coord].r;
    float solvedHeight = Solve(uv);
    solvedHeight = ApplyOperation(origHeight, solvedHeight);

    Result[coord] = float4(solvedHeight, solvedHeight, solvedHeight, 1.0);
}
