#include "FXCommon.hlsl"
#pragma kernel CSMain

cbuffer Params
{
    float MinStepSize;
    float MaxStepSize;
    float StepSize;
    float Direction;
    int Iterations;
}

float Deg2Rad(float d)
{
    float pi = 3.14159265359;
    return d * (pi / 180.0);
}

float Random(float2 p)
{
    float2 k1 = float2(
        23.14069263277926, // e^pi (Gelfond's constant)
        2.665144142690225 // 2^sqrt(2) (Gelfond-Schneider constant)
    );
    return frac(cos(dot(p, k1)) * 12345.6789);
}

float Remap(float val, float r0, float r1)
{
    return val * (r1 - r0) + r0;
}

float Solve(float2 uv)
{
    float radians = Deg2Rad(Direction);
    float2 axis = float2(cos(radians), sin(radians));
    float terrace_height = dot(uv, axis);
    float div = terrace_height / StepSize;
    float flat = floor(div);
    float val = Random(float2(flat, flat + 1));
    val = Remap(val, MinStepSize, MaxStepSize) * Iterations;
    float level = (flat + val) * StepSize;
    return level / 2.0;
}

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float2 uv = GetUV(id);
    int2 coord = int2(id.xy);

    float origHeight = Result[coord].r;
    float solvedHeight = Solve(uv);
    solvedHeight = ApplyOperation(origHeight, solvedHeight);

    Result[coord] = float4(solvedHeight, solvedHeight, solvedHeight, 1.0);
}
