#pragma kernel Effect

struct point_data
{
    float3 p;
};

RWStructuredBuffer<point_data> points;
uint point_count;

cbuffer FXParameters
{
    float direction;
    float steepness;
}

[numthreads(64,1,1)]
void Effect(uint3 id : SV_DispatchThreadID)
{
    uint index = id.y * 8 + id.x;
    if (index >= point_count)
    {
        return;
    }

    // read this point to find its current height
    point_data pnt = points[index];
    float current_height = pnt.p.y;

    // use the parameters to control how the effect behaves
    // a slope is computed, creating a linear gradient along some direction
    float height = current_height + pnt.p.x;

    // write the calculated value to the point to complete the function
    pnt.p.y = height;
    points[index] = pnt;
}
