#pragma kernel Effect

struct vertex
{
    float2 position;
    float height;
};

RWStructuredBuffer<vertex> vertex_buffer;
uint vertex_count;

cbuffer fx_params
{
    float height;
    int operation; // Set, Subtract, Add, Multiply
}

float Solve()
{
    return height;
}

vertex ApplyOperation(vertex vtx, float solved)
{
    switch (operation)
    {
    case 0:
        // Set - Overwrites any existing height
        vtx.height = solved;
        break;

    case 1:
        // Subtract - Reduces existing height by solved
        vtx.height -= solved;
        break;

    case 2:
        // Add - Increases existing height by solved
        vtx.height += solved;
        break;

    case 3:
        // Multiply - Scales existing height by solved
        vtx.height *= solved;
        break;

    default: return vtx;
    }
    return vtx;
}

[numthreads(64,1,1)]
void Effect(uint3 id : SV_DispatchThreadID)
{
    uint index = id.y * 8 + id.x;
    if (index >= vertex_count)
    {
        return;
    }
    vertex vtx = vertex_buffer[index];

    float solved_height = Solve(); // calculate height at this position
    vtx = ApplyOperation(vtx, solved_height);
    vertex_buffer[index] = vtx; // return
}
