#pragma kernel CSMain
#include "FXCommon.hlsl"
#include "SimplexNoise2D.hlsl"

struct Vertex
{
    float3 position;
};

RWStructuredBuffer<Vertex> VertexBuffer;

cbuffer Params
{
    float Size;
    float Steepness;
}

float Solve(float2 uv)
{
    float noise_size = 1.0 - Size; // 0-1 -> 1-0
    uv *= noise_size;
    float noise = SimplexNoise(uv) * Steepness;
    return noise;
}

[numthreads(144,1,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    int index = id.x;
    Vertex vtx = VertexBuffer[index];

    float2 vertex_pos = vtx.position.xz;
    float2 chunk_offset = float2(OffsetX, OffsetY);
    vertex_pos += chunk_offset;

    float existing_height = vtx.position.y;
    float solved_height = Solve(vertex_pos);
    float result_height = ApplyOperation(existing_height, solved_height);

    vtx.position.y = result_height;
    VertexBuffer[index] = vtx;
}
