#include "FXCommon.hlsl"

#pragma kernel CSMain

struct Vertex {
    float3 position;
};
RWStructuredBuffer<Vertex> VertexBuffer;

cbuffer Params
{
    float Direction;
    float Steepness;
    bool Reverse;
}

float Solve(float2 uv)
{
    float rad = radians(Direction);
    float2 dir = float2(cos(rad), sin(rad));
    float result = dot(uv, dir);
    result *= Steepness;
    if (Reverse)
    {
        result *= -1.0;
    }
    return result;
}

[numthreads(121,1,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    int index = id.x;
    Vertex vtx = VertexBuffer[index];

    float2 vertex_pos = vtx.position.xz;
    float2 chunk_offset = float2(OffsetX, OffsetY);
    vertex_pos += chunk_offset;
    
    float existing_height = vtx.position.y;
    float solved_height = Solve(vertex_pos);
    float result_height = ApplyOperation(existing_height, solved_height);
    
    vtx.position.y = result_height;
    VertexBuffer[index] = vtx;
    
    /*float2 uv = GetUV(id);
    int2 coord = int2(id.xy);
    float origHeight = Result[coord].r;
    float solvedHeight = Solve(uv);
    solvedHeight = ApplyOperation(origHeight, solvedHeight);
    Result[coord] = float4(solvedHeight, 0.0, 0.0, 1.0);*/
}
