#include "SimplexNoise2D.hlsl"
#pragma kernel CSMain

RWTexture2D<float4> Result;
float OffsetX;
float OffsetY;
int TextureSize;

cbuffer params
{
    float Height;
    int Operation;
}


[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    // float2 co = float2(OffsetX, OffsetY);
    // float2 uv = float2(id.xy) / TextureSize;
    // uv += co;
    // uv *= 1.0 - 0.1;

    // float n = SimplexNoise(uv);
    // Result[id.xy] = float4(n, n, n, 1.0);
    float n = Height;
    Result[id.xy] = float4(n, n, n, 1.0);
}
