using System.Collections;
using System.Linq;
using DataTypes;
using Internal.Configuration;
using UnityEngine;
using Newtonsoft.Json.Linq;

namespace Internal {
/// <summary>
/// ( in the current form of Voro, its probably not a good idea to create hundreds of these )
/// 
/// Voro is the primary terrain object, existing as a tile/chunk, theoretically usable for infinite maps
/// Unlike a typical terrain system, where you have a mesh of vertices with some heightmap texture
/// this approach uses a pre-generated array of points and fbx mesh instances
///
/// Creating a Voro generates the point data, which is read from a .json
/// file that has been pre-generated by reading the ID and position of
/// every cell in a voronoi diagram. With that same voronoi diagram
/// the cells themselves have been used to produce a set of fbx files
/// in the current version, that is nothing more than a basic extrude+bevel
///
/// When the Voro is in its complete form, existing in the Unity scene, 
/// both arrays for Points and Geometry are used to instance GameObjects
/// for any point, its ID matches a specific .fbx file and the position of
/// the GO is set as the point position
/// </summary>
// ToDo reimplement TableSampling
// ToDo reimplement MultiChunks + InfiniteGrid so that Voros can be generated around a player radius
// ToDo implement method for adjacent Voros to blend together nicely

public class Voro {
    readonly PointArray _pointArray;
    readonly GeometryArray _geometryArray;
    public Point[] Points => _pointArray.points;
    public Geometry[] Geometry => _geometryArray.Geo;

    Voro _original;
    JsonConfig _config;
    // ToDo decide on the actual steps of when a json is used, and height is set
    // the points from DemoTable dont actually need to be set by anything else
    // Voro always needs Points, its pointless for the user to need to set those
    
    public Voro(string configName, Vector3 offset) {
        
        // point data in json file is used to build the cells for this voro
        _pointArray = new PointArray(ResourceHelper.LoadVoroPoints());
        _geometryArray = new GeometryArray(_pointArray);
        
        // read the configuration
        // get the JsonConfig which contains the configuration objects for the voro height
        _config = new JsonConfig(configName);
        
        // configure the height so the voro is built in its finished form
        ConfigurePointHeight(offset);
        
        OnCreation();
    }
    
    void OnCreation() {
        // ToDo clone the voro for it to be restored if edited during runtime
        // clone this voro to act as a snapshot, allows this current voro to be safely
        // modifiable, and can easily be reset
    }

    /*public static bool BuildVoro(string configName, Vector3 offset, out Voro voro) {
        return true;
    }*/

    bool ConfigurePointHeight(Vector3 offset) {

        // this class uses a configuration json and can read the data inside it
        // this configuration is to alter the height value of all the voro points
        // the config holds a set of values which are used to form an instruction
        // this instruction is designed to manipulate the height value in a way
        // that allows the look of the terrain to be directed by the user
        // multiple instructions can be stored in the configuration file
        VoroHeight voroHeight = new VoroHeight(_config);

        // ToDo using VoroHeight should be able to update the points right away
        // that would streamline "new VoroHeight -> GetHeight -> ApplyHeight"
        // when VoroHeight gets created its only for the reason of setting height
        // its silly having 3 steps in order to do a single step of "ApplyHeight"
        
        
        // get an array of float values, which are the calculated point heights
        voroHeight.GetHeight(_pointArray, offset, out var height);
        
        // apply the height value to each point that is in this voro
        ApplyHeight(height);
        void ApplyHeight(float[] heightValues) {
            for (var i = 0; i < height.Length; i++) {
                // get the position of each point
                var newPos = _pointArray.points[i].position;
                // set the height value in the point
                newPos.y = height[i];
                // set the new position of the point, applying the height value
                _pointArray.points[i].position = newPos;
            }
        }

        return true;
    }

    // ToDo implement OnConfigured and the ability to make sure all heights are valid
    // OnConfigured() {
    //     // 1) finalize check to ensure the requested configuration is valid
    //     // ie terrain slope+elevation is between a constant range, correcting errors if bad
    // }
    // ToDo allow the Voro to be deleted from the game world, disconnecting it from anything else
    // OnDeletion() {
    //     // 1) invoke to declare this space is now empty, so anything still using it
    //     // has to stop what its doing (the voro exploded and died rip)
    // }
    // ToDo let the Voro be updated, so changes can be applied during runtime
    // OnUpdate() {
    //     // 1) apply any proposed changes to the voro, updating parameters etc
    // }
}
}
